### PR TITLE
Add json array input decode with try catch to fall back to string splitting

### PR DESCRIPTION
**Pull request by darakian**
This PR adds a bulk message decode route compatible with rsyslog's jsonarray output. In my testing all that was required was to decode the raw message which was nice. Discussion on the subject started here
https://github.com/mozilla/MozDef/issues/1246

I'm not sure what the `# don't post the items telling us where to post things..` part was about so I just copied over the publishing logic.

Edit: Rsyslog docs for http batch formats
https://www.rsyslog.com/doc/v8-stable/configuration/modules/omhttp.html#batch-format

### CODE REVIEW

**Comment by darakian** [comment]
Can I get a comment on if this behavior is desired?

**Comment by pwnbus** [comment]
@darakian I think the behavior is desired, but looking quickly, won't this post the bulk messages twice?

**Comment by darakian** [comment]
Oh shit you're right. I guess it should return after the first post. No worries on the delay, I just wanted to be sure that I'm not working against the grain. Give me a bit and I'll update the PR.

**Comment by darakian** [comment]
@pwnbus Just pushed an update. I moved a few comments around in hopes that it makes things a bit clearer for the next person. Let me know if you agree.

**Comment by Phrozyn** [comment]
@darakian lines 44 and 56 are failing formatting here:

/loginput/index.py:44:13: E261 at least two spaces before inline comment
./loginput/index.py:56:29: E261 at least two spaces before inline comment

If you can fix those, this should pass.
Thanks!

**Comment by darakian** [comment]
@Phrozyn Pushed an update. My bad on the whitespace.

**Pull request merged**
