### PR TITLE
Fix region parameter in connect_sqs

### PR DESCRIPTION
**Pull request by pwnbus**
This "might" be a fix for https://github.com/mozilla/MozDef/issues/1380

### CODE REVIEW

**Comment by pwnbus** [comment]
FYI this is untested, so I'd like to see if we could test this before merging perhaps?

I also tried to see if we needed to modify the calls to access S3 buckets via regionless parameters, but we may not need to make any modifications? (not entirely sure)

**Comment by pwnbus** [comment]
We may need to do a similar patch to https://github.com/mozilla/MozDef/blob/master/mq/esworker_cloudtrail.py#L231-L235

**Comment by pwnbus** [comment]
Verified that this is working, so it's ready to review/merge.

**Comment by pwnbus** [comment]
@gene1wood it wasn't a breaking change since we were passing parameters via position when calling that, but I've updated it to be consistent in https://github.com/mozilla/MozDef/pull/1383/commits/d7437b46197a7cf92f8892dbb4d5a59515ef4d6e

**Comment by gene1wood** [comment]
Aha right, [it's called positionally](https://github.com/mozilla/MozDef/pull/1383/files#diff-252fe61df1b95fcce77d038d7838f7f2R9) got it. Cool, LGTM

**Pull request merged**
