### PR TITLE
Corrected mozdefalerts init script and added supervisord.alerts.conf

### PR DESCRIPTION
**Pull request by Phrozyn**
corrected mozdefalerts init script to avoid race conditions with other supervisord processes, also adding supervisord.alerts.conf to repo.

### CODE REVIEW

**Comment by Phrozyn** [comment]
fixes #359

**Comment by mpurzynski** [comment]
r+

**Comment by pwnbus** [comment]
r+

**Comment by Phrozyn** [comment]
closes #359

**Pull request merged**
