### PR TITLE
Update blocklist to only look at 7 days of attackers

### PR DESCRIPTION
**Pull request by pwnbus**
References a possible fix for https://github.com/mozilla/MozDef/issues/353

Signed-off-by: Brandon Myers bmyers@mozilla.com

### CODE REVIEW

**Comment by Phrozyn** [comment]
+r - requested testing on mozdefqa1 before committing.

**Comment by jeffbryner** [comment]
why do we only care about 7 days?

**Comment by pwnbus** [comment]
@jeffbryner @Phrozyn and I talked about this, and thought maybe it's best to bring up during our next infosec meeting real quick to get people's thoughts?

**Comment by jeffbryner** [comment]
OK

**Comment by Phrozyn** [comment]
Notes taken from an offline discussion:

- We should be deliberate about the block time value
- Distinguish first offense/second offense?
- Possible signals: if the IP is from AWS => shorter block
- Incorporate into roadmap for MozDef

**Comment by Phrozyn** [comment]
I had to raise the number of IPs blacklisted in MozDef due to going over 2000, then over 3000.
We should implement this for now, maybe change it to 3 months of aging instead of 7 days, until we have more time to really make something beautiful out of this.

**Comment by pwnbus** [comment]
Modified to reflect 3 months

**Comment by pwnbus** [comment]
Closing PR since this change is no longer needed.

**Pull request closed without merging**
