### PR TITLE
Try except on alert import

### PR DESCRIPTION
**Pull request by darakian**
This should prevent a single bad alert from taking down the alerts container as a whole.

### CODE REVIEW

**Comment by pwnbus** [comment]
Great idea! One thing worth noting, all our PR status' will fail as a result of a bug in one of our dependencies, we're actively trying to work through this, and will get resolved as soon as https://github.com/mozilla/MozDef/pull/1032 is merged (should be done in the next couple hours at most hopefully)

**Comment by darakian** [comment]
Ya, no worries and no rush.

**Comment by pwnbus** [comment]
Should be all set if you merge master into this branch!

**Comment by darakian** [comment]
@pwnbus Ready to be reviewed.

**Pull request merged**
