### PR TITLE
Remove free-form 'Contributor:' text from code. Fixes #407

### LINKED ISSUE #407: Remove free-form "Contributor:" text from individual code refs
Just a suggestion, I feel like this is more of a Perl/pre-SCM era convention to tag modules or contributions in the code itself.  Recommend removing those in favor of having the SCM tell the story for us.

### PR DESCRIPTION
**Pull request by yashmehrotra**
I used the following script to make the changes.

```
In [2]: for f in all_files:
   ...:     fp = open(f, 'r+')
   ...:     text = re.sub(r'(?s)(# Contributors:.*?)(?:(?:\r*\n){2})', '\n', fp.read())
   ...:     fp.seek(0)
   ...:     fp.truncate()
   ...:     fp.write(text)
```

### CODE REVIEW

**Comment by pwnbus** [comment]
@yashmehrotra Sorry about the failed unit tests (the last round), I've pushed a fix to master, if you update your branch with specifically https://github.com/mozilla/MozDef/pull/579/commits/4f37cb39bf56abb75886637d32b96c2e5b74f58e , the tests should pass.

**Comment by pwnbus** [comment]
I've tested this change with merging with master and everything passes (https://travis-ci.org/mozilla/MozDef/jobs/325204550) so this is safe to merge.

**Comment by pwnbus** [comment]
Very nicely done!

**Comment by yashmehrotra** [comment]
@pwnbus Thanks 😄

**Pull request merged**
