### PR TITLE
Add decom notice to readme

### PR DESCRIPTION
**Pull request by pwnbus**
😢

### CODE REVIEW

**Comment by gene1wood** [comment]
Maybe no need for the "no warranty" note since the absence of warranty is already part of the open source license.

**Comment by pwnbus** [comment]
@gene1wood Removed the warranty line.

**Comment by claudijd** [comment]
r+

**Review by claudijd — APPROVED** [review]

**Review by gene1wood — APPROVED** [review]

**Comment by claudijd** [comment]
🍻

**Pull request merged**
