### PR TITLE
improvements to dockerfile

### PR DESCRIPTION
**Pull request by cglewis**
- update docs to match
- set default cmd so it can run in the background
- combine commands to reduce size (savings of almost 250mb)
- reorder commands to improve caching when building
- fix up whitespace

### CODE REVIEW

**Comment by Phrozyn** [comment]
Thanks for the commit! 
I'll test these changes out and commit once we've done that.

**Comment by pwnbus** [comment]
@cglewis We apologize for the dead air here. We were actively doing development on a private project, but have just recently merged these changes into this public repo (this repo will be the one used going forward FYI).

As part of the merging of the code bases, it looks like we've encountered a merge conflict for these changes. Since you're operating on a fork, we have a couple options here:
1. You can fix the merge changes yourself on your fork and then I'll merge this PR
2. I can create a new branch, and cherry-pick your changes (so that we retain the commit history), and will resolve the merge conflicts myself within the branch. I will then close out this PR, and reopen a new one pointing to the new branch.

I realize this PR was quite old and was just sitting here, so in my opinion, option 2 would be best and easiest for all.

**Comment by cglewis** [comment]
@pwnbus thanks for following up. option 2 sounds good. let me know if you need me to do anything.  thanks!

**Comment by pwnbus** [comment]
I've created https://github.com/mozilla/MozDef/pull/401 which resolves the merge conflict, so I'm closing this PR. 

Thanks for the contribution!

**Pull request closed without merging**
