### PR TITLE
Remove blue page visualizations

### PR DESCRIPTION
**Pull request by pwnbus**
This also removes the idea of an Attacker, in favor of using an alert action to do the blocking from https://github.com/mozilla/MozDef/pull/1567

### CODE REVIEW

**Comment by jeffbryner** [comment]
😢

**Comment by pwnbus** [comment]
@jeffbryner We're definitely pouring one out for the ogres :) 

We just felt that the kibana visualizations are the better, more supported route.

**Comment by jeffbryner** [comment]
Understood, ogres aren't for everyone ;-] They'll live on in forks 🍴

**Comment by Phrozyn** [comment]
Farewell dearest Ogres

**Pull request merged**
