### PR TITLE
Elasticsearch 6 Upgrade

### PR DESCRIPTION
**Pull request by pwnbus**
This PR contains all of the breaking code changes that is required for the Elasticsearch 6 upgrade.

These changes are NOT backwards compatible with Elasticsearch 5. We are now requiring use of Elasticsearch 6.

### CODE REVIEW

**Comment by Phrozyn** [comment]
Errors consist of the following:
RequestError: RequestError(400, u'illegal_argument_exception', u'The provided expression [events] matches an alias, specify the corresponding concrete indices instead.')

**Comment by pwnbus** [comment]
> Errors consist of the following:
> RequestError: RequestError(400, u'illegal_argument_exception', u'The provided expression [events] matches an alias, specify the corresponding concrete indices instead.')

@Phrozyn Could you provide more context on this? What's the service that's erroring out? Do you have the full stack trace?

**Comment by pwnbus** [comment]
Ohh, it's from the build status, interesting.

**Comment by Phrozyn** [comment]
> > Errors consist of the following:
> > RequestError: RequestError(400, u'illegal_argument_exception', u'The provided expression [events] matches an alias, specify the corresponding concrete indices instead.')
> 
> @Phrozyn Could you provide more context on this? What's the service that's erroring out? Do you have the full stack trace?

It's in the travis output. Seems to be this part of the unit test
tests/unit_test_suite.py:63: in setup_elasticsearch
    self.es_client.create_alias_multiple_indices('events-weekly', ['events', 'events-previous'])

It's passing an alias, but in es6.x you can't apply an alias to an alias, only to indices.
https://www.elastic.co/guide/en/elasticsearch/reference/6.7/breaking-changes-6.0.html#_indices_aliases_api_resolves_indices_expressions_only_against_indices

**Comment by pwnbus** [comment]
@Phrozyn I created https://github.com/mozilla/MozDef/pull/1178/commits/e3eca4222b478357d7480337fe6c1ed8029fb72c that should fix the build error that you pasted!

**Pull request merged**
